bridge/urls.py
from django.urls import path
from . import views

app_name = 'bridge'

urlpatterns = [
    path('', views.bridge, name='bridge'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

jadwalku/urls.py
from django.urls import path
from . import views

app_name = 'jadwalku'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    path('hapus/<int:id>', views.delete_matkul, name='hapus'),
    path('tambah-jadwal', views.tambah, name='tambah'),
]

story2/urls.py
from django.urls import path
from . import views

app_name = 'story2'

urlpatterns = [
    path('', views.index, name='index'),
]

story3/urls.py
from django.urls import path
from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='index'),
]

story_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.shortcuts import redirect

from jadwalku import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bridge.urls')),
    path('story1/', include('homepage.urls')),
    path('story2/', RedirectView.as_view(url='https://www.figma.com/file/OfcqSfnJe6P7q87GmfLbef/Story2'), name='story2-figma'),
    path('story3/', include('story3.urls')),
    path('story4/', views.redirek),
    path('jadwalku/', include('jadwalku.urls')),
]

bridge/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

jadwalku/models.py
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.db import models

# Create your models here.
class Semester(models.Model):
    
    name = "Semester"

    class Term(models.TextChoices):
        GENAP = 'Genap', _('Genap')
        GANJIL = 'Ganjil', _('Ganjil')
    
    term = models.CharField(max_length=6, choices=Term.choices, default=Term.GANJIL)
    tahun_ajaran = models.CharField(max_length=9) 

    class Meta:
        verbose_name = _("Semester")
        verbose_name_plural = _("Semesters")

    def __str__(self):
        return '%s %s' % (self.term, self.tahun_ajaran)

    def get_absolute_url(self):
        return reverse("Semester_detail", kwargs={"pk": self.pk})


class MataKuliah(models.Model):
    
    name = "MataKuliah"

    SKS = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
    ]

    nama_matkul = models.CharField(max_length=50)
    deskripsi   = models.TextField()
    kelas       = models.CharField(max_length=50)
    kredit      = models.IntegerField(choices=SKS, default=4)
    pengajar    = models.CharField(max_length=100)
    semester    = models.ForeignKey("Semester", verbose_name="semester", on_delete=models.CASCADE, default="Ganjil 2020/2021")

    waktu_dibuat= models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "MataKuliah"
        verbose_name_plural = "MataKuliahs"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("MataKuliah_detail", kwargs={"pk": self.pk})

story2/models.py
from django.db import models

# Create your models here.

jadwalku/forms.py
from django import forms
from .models import MataKuliah
from crispy_forms.helper import FormHelper

class MataKuliahForm(forms.ModelForm):
    helper = FormHelper()
    
    class Meta:
        model = MataKuliah
        fields = "__all__"
    
    # nama_matkul = forms.CharField(
    #     label="Nama Mata Kuliah", 
    #     error_messages=["Mohon isi nama mata kuliah"], 
    #     max_length=, 
    #     required=False
    # )
    # deskripsi   = forms.Textarea()
    # kelas       = forms.CharField()
    # kredit      = forms.IntegerField(max_value=6, min_value=1)
    # pengajar    = forms.CharField()
    # semester    = forms.ChoiceField(, choices=[CHOICES], required=False)
    

bridge/views.py
from django.shortcuts import render

# Create your views here.

def bridge(request):
    return render(request, 'bridge.html')

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1.html')

jadwalku/views.py
from django.shortcuts import render, redirect
from .forms import MataKuliahForm
from .models import MataKuliah

# Create your views here.
def index(request):
    mata_kuliah = MataKuliah.objects.all()
    context = {'mata_kuliah' : mata_kuliah}
    return render(request, 'jadwalku.html', context=context)

def tambah(request):
    if request.method == "POST":
        form = MataKuliahForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('jadwalku:index')
    else:
        context = {
            'form': MataKuliahForm(),
        }
        return render(request, 'tambah-jadwal.html', context=context)
    
def detail(request, id):
    context = {
        'matkul' : MataKuliah.objects.get(id=id)
    }
    return render(request, 'jadwalku-detail.html', context=context)

def delete_matkul(request, id):
    MataKuliah.objects.get(id=id).delete()
    return redirect('jadwalku:index')

def redirek(request):
    return redirect('jadwalku:index')

story2/views.py
from django.shortcuts import render 

# Create your views here.
def index(request):
    return render(request, 'index.html')

story3/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

bridge/templates/bridge.html
{% extends 'base.html' %}

{% load static %}
{% block head %}
  <title>Dennis Walangadi</title>
  <meta name="description" content="See my pepew stories!">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="Pepew Submissions">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Dennis' Stories">
{% endblock head %}

{% block style %}
  <link rel="icon" type="image/x-icon" href="{% static 'images/man.svg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Open+Sans&display=swap" rel="stylesheet">
{% endblock style %}

{% block script %}
  <script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
{% endblock script %}

{% block main %}
<div class="grid grid-centered">
  <div class="grid-cell">
    <nav class="header-nav">
      <a class="header-logo toggle-dark-mode" title="Dennis Walangadi">DNSWD</a>
    </nav>

    <div class="about">
      
      <h1>Hi, I'm Dennis!</h1>
      <p>
        Here's some of my submissions for my web designing and programming course.
      </p>

      <h1>Stories</h1>
      <div>
        <ul>
          <li>
            <h3><a href="{% url 'homepage:index' %}">Story 1</a></h3>
          </li>
          <li>
            <h3><a href="https://www.figma.com/file/OfcqSfnJe6P7q87GmfLbef/Story2" target="_blank">Story 2</a></h3>
          </li>
          <li>
            <h3><a href="{% url 'story3:index' %}">Story 3</a></h3>
          </li>
          <li>
            <h3><a href="#">Story 4</a> (this page, and a nav button)</h3>
          </li>
          <li>
            <h3><a href="{% url 'jadwalku:index' %}">Story 5</a></h3>
          </li>
        </ul>
      </div>

    </div>

    <footer class="footer">
      <p>
        © 2020 Dennis A. Walangadi
      </p>
    </footer>
  </div>
</div>

<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
{% endblock main %}

homepage/templates/story1.html
{% load static %}

  {% block head %}
  <title>Dennis Walangadi</title>
  <meta name="description" content="Hell yeah that's me!">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="About me">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Dennis Walangadi">

  <link rel="icon" type="image/x-icon" href="{% static 'images/man.svg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Open+Sans&display=swap" rel="stylesheet">
  {% endblock head %}

  {% block script %}
  <script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
  {% endblock script %}

  {% block main %}
  {% include "navigation.html" %}
    <div class="grid grid-centered">
      <div class="grid-cell">
        <nav class="header-nav">
          <a class="header-logo toggle-dark-mode" title="Dennis Walangadi">Dennis Walangadi</a>
        </nav>

        <div class="about">
          <img class="avatar inverted" src="{% static 'images/me.jpg' %}" alt="My Face" title="Hell yeah that's me!">
          <table>
            <tr>
              <th>Name</th>
              <th>: </th>
              <td>Dennis Al Baihaqi Walangadi</td>
            </tr>
            <tr>
              <th>Occupation&nbsp;</th>
              <th>: </th>
              <td>Student @ <a href="https://www.cs.ui.ac.id/" target="_blank">Fasilkom, Universitas Indonesia</a></td>
            </tr>
            <tr>
              <th>NPM</th>
              <th>: </th>
              <td><code>1906400141</code></td>
            </tr>
            <tr>
              <th>Batch</th>
              <th>: </th>
              <td>2019</td>
            </tr>
            <tr>
              <th>Hobby</th>
              <th>: </th>
              <td>Code, YouTube, Surf the Internet</td>
            </tr>

          </table>
          <h1>Short Bio</h1>
          <p>
            I aim to be a full-stack developer. I love exploring open-source projects on Github. I'm trying to learn web
            dev lately. Mostly Django, Deno, Next.js, and Node.js. <br>
            I also love to cook! I usually cook garlic bread, my favorite comfort food.
          </p>

          <h1>Education Timeline</h1>
          <div id="timeline-content">
            <ul class="timeline">
              <li class="event">
                <h3>Faculty of Computer Science, University of Indonesia</h3>
                <p>2019 — Now</p>
              </li>
              <li class="event">
                <h3>Muhammadiyah 4 Highschool</h3>
                <p>2015 — 2018</p>
              </li>
              <li class="event">
                <h3>Maria Immaculata Marsudirini Junior Highschool</h3>
                <p>2012 — 2015</p>
              </li>
              <li class="event">
                <h3>Cawang 01 Public Elementary School</h3>
                <p>2006 — 2012</p>
              </li>
            </ul>
          </div>

          <h3 style="text-align: center;">Reach Me Out!</h3>
          <ul class="header-links">
            <li><a target="_blank" title="GitHub" href="https://github.com/dnswd"><i class="fab fa-github"></i></a></li>
            <li><a target="_blank" title="LinkedIn" href="https://www.linkedin.com/in/denniswd/"><i class="fab fa-linkedin"></i></a></li>
            <li><a target="_blank" title="Twitter" href="https://twitter.com/dnnswd"><i class="fab fa-twitter"></i></a></li>
            <li><a target="_blank" title="Instagram" href="https://www.instagram.com/denniswalangadi/"><i
                  class="fab fa-instagram"></i></a></li>
            <li><a target="_blank" title="Line Messenger" href="https://line.me/R/ti/p/dennisaw2000"><i class="fab fa-line"></i></a></li>
            <li><a target="_blank" title="Email" href="mailto:dennis.al@ui.ac.id"><i class="fas fa-envelope"></i></a></li>
          </ul>

        </div>

        <footer class="footer">
          <p>
            © 2020 Dennis A. Walangadi
          </p>
        </footer>
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  {% endblock main %}
  

jadwalku/templates/jadwalku-detail.html
{% load static %}

  {% block head %}
  <title>Dennis Walangadi | JadwalKu</title>
  <meta name="description" content="These things keeps me busy">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="JadwalKu">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="JadwalKu | Dennis Walangadi">

  <link rel="icon" type="image/x-icon" href="{% static 'images/man.svg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/jadwalku.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Open+Sans&display=swap" rel="stylesheet">
  {% endblock head %}

  {% block script %}
  <script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
  {% endblock script %}

  {% block main %}
  {% include "navigation.html" %}
    <div class="grid grid-centered">
      <div class="grid-cell">
        <nav class="header-nav">
          <a class="header-logo toggle-dark-mode" title="JadwalKu">JADWALK U</a>
        </nav>
        
        <div class ="about">
            <h1>{{ matkul.nama_matkul }}</h1>
            <code>Created at {{matkul.waktu_dibuat }}</code>
            <table>
                <tr>
                <th>Kelas</th>
                <th>: </th>
                <td>{{ matkul.kelas }}</td>
                </tr>
                <tr>
                <th>Jumlah SKS&nbsp;</th>
                <th>: </th>
                <td>{{ matkul.kredit }}</td>
                </tr>
                <tr>
                <th>Pengajar</th>
                <th>: </th>
                <td>{{ matkul.pengajar }}</td>
                </tr>
                <tr>
                <th>Semester</th>
                <th>: </th>
                <td>{{ matkul.semester }}</td>
                </tr>

            </table>
            <h1>Deskripsi</h1>
            <p>{{ matkul.deskripsi }}</p>
        </div>

        <div class="tambah-jadwal">
                <a href="{% url 'jadwalku:index' %}"><div class="round-button button-accent">Kembali</div></a>
                <a href="{% url 'jadwalku:hapus' matkul.id %}"><div class="round-button button-accent warn">Hapus</div></a>
            </div>

        <footer class="footer">
          <p>
            © 2020 Dennis A. Walangadi
          </p>
        </footer>
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  {% endblock main %}
  

jadwalku/templates/jadwalku.html
{% load static %}

  {% block head %}
  <title>Dennis Walangadi | JadwalKu</title>
  <meta name="description" content="This things keeps me busy">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="JadwalKu">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="JadwalKu | Dennis Walangadi">

  <link rel="icon" type="image/x-icon" href="{% static 'images/man.svg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/jadwalku.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Open+Sans&display=swap" rel="stylesheet">
  {% endblock head %}

  {% block script %}
  <script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
  {% endblock script %}

  {% block main %}
  {% include "navigation.html" %}
    <div class="grid grid-centered">
      <div class="grid-cell">
        <nav class="header-nav">
          <a class="header-logo toggle-dark-mode" title="JADWALKU">JADWALK U</a>
        </nav>
        
        <div class ="canvas">
            <div class="tambah-jadwal">
                <a href="{% url 'jadwalku:tambah' %}"><div class="round-button button-accent">+ Jadwal Baru</div></a>
            </div>

            <div class="deck">
                <div class="deck-grid">
                    <ul>
                      {% for matkul in mata_kuliah %}
                        <a href="{% url 'jadwalku:detail' matkul.id %}">
                          <li>
                              <h1>{{ matkul.nama_matkul }}</h1>
                              <code class="small">{{ matkul.semester }} - {{ matkul.kredit }}</code>
                          </li>
                        </a>  
                      {% endfor %}
                    </ul>
                </div>
            </div>

        </div>

        <footer class="footer">
          <p>
            © 2020 Dennis A. Walangadi
          </p>
        </footer>
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  {% endblock main %}
  

jadwalku/templates/tambah-jadwal.html
{% load static %}
{% load crispy_forms_tags %}
{% comment %} {% crispy form form.helper %} {% endcomment %}

  {% block head %}
  <title>Dennis Walangadi</title>
  <meta name="description" content="Hell yeah that's me!">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="JadwalKu">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="JadwalKu | Dennis Walangadi">

  <link rel="icon" type="image/x-icon" href="{% static 'images/man.svg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&family=Open+Sans&display=swap" rel="stylesheet">
  {% endblock head %}

  {% block script %}
  <script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
  {% endblock script %}

  {% block main %}
  {% include "navigation.html" %}
    <div class="grid grid-centered">
      <div class="grid-cell">
        <nav class="header-nav">
          <a class="header-logo toggle-dark-mode" title="JadwalKu">JADWALK U</a>
        </nav>

        <div class="about">

          <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit">Submit</button>
          </form>

        </div>

        <footer class="footer">
          <p>
            © 2020 Dennis A. Walangadi
          </p>
        </footer>
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  {% endblock main %}
  

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    {% block head %}
    {% endblock head %}

    {% block script %}
    {% endblock script %}

    {% block style %}
    {% endblock style %}


    {% block body %}
    {% endblock body %}

        {% block main %}
        {% endblock main %}


</html>

templates/navigation.html
<style>
.bridge {
  position: relative;
  z-index: 99;
  font-family: 'Open Sans', sans-serif;;
}
.bridge-back {
  width: 100px;
  padding-top: 5px;
  padding-bottom: 5px;
  text-align: center;
  color: #000;
  text-transform: uppercase;
  font-weight: 600;
  margin-left: 30px;
  margin-bottom: 30px;
  cursor: pointer;
  display: inline-block;
  position: fixed;
  z-index: 999;
  top: 23px;
  left: -5px;
}

.bridge-accent {
  background: linear-gradient(300deg, rgba(240,147,251,1) 0%,   rgba(245,87,108,1) 100%);
  border-radius: 100px;
  -webkit-transition: all .15s ease-in-out;
  transition: all .15s ease-in-out;
  color: #fff;
}
.bridge-accent:hover {
  filter: drop-shadow(0 5px 5px rgb(0,0,0,0.5));
  transform: translate(0px, -2px);
}
</style>


<div class="bridge">
  <a href="{% url 'bridge:bridge' %}"><div class="bridge-back bridge-accent">← Back</div></a>
</div>


<script>
var prevScrollpos = window.pageYOffset;
window.onscroll = function() {
  var currentScrollPos = window.pageYOffset;
  if (prevScrollpos > currentScrollPos) {
    document.getElementsByClassName("bridge-back")[0].style.top = "30px";
  } else {
    document.getElementsByClassName("bridge-back")[0].style.top = "-60px";
  }
  prevScrollpos = currentScrollPos;
}
</script>